FROM ruby:2.2-alpine

RUN apk add --update \
    git \
    mariadb-dev \
    postgresql-dev \
    ruby-dev \
    libxml2-dev \
    libxslt-dev \
    nodejs \
    tzdata \
    build-base \
  && rm -rf /var/cache/apk/*

# Use libxml2, libxslt a packages from alpine for building nokogiri
RUN bundle config build.nokogiri --use-system-libraries

RUN mkdir /app
WORKDIR /app
ADD . /app
