---
test:
  build: "."
  dockerfile: Dockerfile.ci
  working_dir: "/app"
  volumes:
    - ~/bundle:/usr/local/bundle
  environment:
    RAILS_ENV: test
    MYSQL_HOST: mysql
    MYSQL_PORT: '3306'
  links:
  - mysql
mysql:
  image: mysql:5.6.23
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
